# -*- coding: utf-8 -*-
"""Kafka.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15QGHLyOGijU-z6sKyKvWXV9T48tTAed-
"""

!curl -sSOL https://downloads.apache.org/kafka/3.6.0/kafka_2.12-3.6.0.tgz
!tar -xzf kafka_2.12-3.6.0.tgz

!./kafka_2.12-3.6.0/bin/zookeeper-server-start.sh -daemon ./kafka_2.12-3.6.0/config/zookeeper.properties
!./kafka_2.12-3.6.0/bin/kafka-server-start.sh -daemon ./kafka_2.12-3.6.0/config/server.properties

!./kafka_2.12-3.6.0/bin/kafka-topics.sh --create --bootstrap-server 127.0.0.1:9092 --replication-factor 1 --partitions 1 --topic TestTopic

!./kafka_2.12-3.6.0/bin/kafka-topics.sh --describe --bootstrap-server 127.0.0.1:9092 --topic TestTopic

!./kafka_2.12-3.6.0/bin/kafka-console-producer.sh --topic TestTopic --bootstrap-server 127.0.0.1:9092

!./kafka_2.12-3.6.0/bin/kafka-console-consumer.sh --topic TestTopic --from-beginning --bootstrap-server 127.0.0.1:9092

!pip install kafka-python

from kafka import KafkaProducer
topic_name = 'TestTopic'
kafka_server = 'localhost:9092'
producer = KafkaProducer(bootstrap_servers=kafka_server)
producer.send(topic_name, b'Hello Kafka Python!!!')
producer.flush()

from kafka import KafkaConsumer
topic_name = 'TestTopic'
consumer = KafkaConsumer (topic_name,bootstrap_servers='127.0.0.1:9092', auto_offset_reset='earliest')
print(consumer)
for message in consumer:
  print(message)